### ISSUE TITLE
[Helios] Clear current frame after stop is called

### ISSUE THREAD

**Issue by SpaceK33z** [Volst/laser-dac#48]
Currently when you use a Helios device, after you call the `stop()` method on it, the last sent frame will still be visible on the laser. Instead, it should clear this frame.

**Comment by rebane2001** [comment]
Not sure if related, but when using the Python API, when I send empty frames it also keeps the previous ones
Can't find a way to clear it either

**Comment by SpaceK33z** [comment]
Thanks, that's interesting! At the moment I don't clear the frames at all when calling stop, so I'm curious if I'm going to be having the same issue.

**Comment by SpaceK33z** [comment]
Calling `HeliosLib.SetShutter(dacNum, false)` when closing seems to work (fixed this a while ago already).
