### ISSUE TITLE
How to add support for a new device?

### ISSUE THREAD

**Issue by cgreening** [Volst/laser-dac#77]
Hi,

I'm working on an ESP32 based board that will drive laser galvos. At the moment I'm playing ILDA files locally but would like to integrate it with laser-dac.

The board is WiFi enabled so streaming over a WebSocket, TCP or HTTP connection will be pretty straightforward.

Where should I start in adding a new device to the system?

Thanks
Chris

**Comment by SpaceK33z** [comment]
Laser-dac is modular and consists of multiple packages. Each package represents a device. For example for the Laserdock there's this one: https://github.com/Volst/laser-dac/tree/master/packages/laserdock. So best is to copy the code from there for example and then modify it to work with your own.

**Comment by afronorana** [comment]
@cgreening , did you manage figure it out?

**Comment by cgreening** [comment]
I got slightly sidetracked and ended up writing my own later driver for the ESP32:

https://github.com/atomic14/esp-asteroids
and
https://github.com/atomic14/esp32-laser-show
